package com.ruike.itf.domain.vo;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.apache.commons.lang.StringUtils;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Optional;

import static com.ruike.itf.infra.constant.ItfConstant.ProcessStatus.ERROR;

/**
 * <p>
 * 质量文件解析接口行
 * </p>
 *
 * @author Aidan.Zhu yonghui.zhu@hand-china.com 2021/4/6 13:58
 */
@Data
public class QualityAnalyzeLineIfaceVO {
    @ApiModelProperty(value = "类型")
    private String type;
    @ApiModelProperty(value = "物料批编码")
    private String materialLotCode;
    @ApiModelProperty(value = "物料批Id")
    private String materialLotId;
    @ApiModelProperty(value = "数量")
    private BigDecimal quantity;
    @ApiModelProperty(value = "物料编码")
    private String materialCode;
    @ApiModelProperty(value = "物料Id")
    private String materialId;
    @ApiModelProperty(value = "处理日期")
    private Date processDate;
    @ApiModelProperty(value = "处理消息")
    private String processMessage;
    @ApiModelProperty(value = "处理状态(N/P/E/S:正常/处理中/错误/成功)")
    private String processStatus;
    @ApiModelProperty(value = "检验项目1")
    private String test1;
    @ApiModelProperty(value = "检验项目2")
    private String test2;
    @ApiModelProperty(value = "检验项目3")
    private String test3;
    @ApiModelProperty(value = "检验项目4")
    private String test4;
    @ApiModelProperty(value = "检验项目5")
    private String test5;
    @ApiModelProperty(value = "检验项目6")
    private String test6;
    @ApiModelProperty(value = "检验项目7")
    private String test7;
    @ApiModelProperty(value = "检验项目8")
    private String test8;
    @ApiModelProperty(value = "检验项目9")
    private String test9;
    @ApiModelProperty(value = "检验项目10")
    private String test10;
    @ApiModelProperty(value = "检验项目11")
    private String test11;
    @ApiModelProperty(value = "检验项目12")
    private String test12;
    @ApiModelProperty(value = "检验项目13")
    private String test13;
    @ApiModelProperty(value = "检验项目14")
    private String test14;
    @ApiModelProperty(value = "检验项目15")
    private String test15;
    @ApiModelProperty(value = "检验项目16")
    private String test16;
    @ApiModelProperty(value = "检验项目17")
    private String test17;
    @ApiModelProperty(value = "检验项目18")
    private String test18;
    @ApiModelProperty(value = "检验项目19")
    private String test19;
    @ApiModelProperty(value = "检验项目20")
    private String test20;
    @ApiModelProperty(value = "检验项目21")
    private String test21;
    @ApiModelProperty(value = "检验项目22")
    private String test22;
    @ApiModelProperty(value = "检验项目23")
    private String test23;
    @ApiModelProperty(value = "检验项目24")
    private String test24;
    @ApiModelProperty(value = "检验项目25")
    private String test25;
    @ApiModelProperty(value = "检验项目26")
    private String test26;
    @ApiModelProperty(value = "检验项目27")
    private String test27;
    @ApiModelProperty(value = "检验项目28")
    private String test28;
    @ApiModelProperty(value = "检验项目29")
    private String test29;
    @ApiModelProperty(value = "检验项目30")
    private String test30;
    @ApiModelProperty(value = "检验项目31")
    private String test31;
    @ApiModelProperty(value = "检验项目32")
    private String test32;
    @ApiModelProperty(value = "检验项目33")
    private String test33;
    @ApiModelProperty(value = "检验项目34")
    private String test34;
    @ApiModelProperty(value = "检验项目35")
    private String test35;
    @ApiModelProperty(value = "检验项目36")
    private String test36;
    @ApiModelProperty(value = "检验项目37")
    private String test37;
    @ApiModelProperty(value = "检验项目38")
    private String test38;
    @ApiModelProperty(value = "检验项目39")
    private String test39;
    @ApiModelProperty(value = "检验项目40")
    private String test40;
    @ApiModelProperty(value = "检验项目41")
    private String test41;
    @ApiModelProperty(value = "检验项目42")
    private String test42;
    @ApiModelProperty(value = "检验项目43")
    private String test43;
    @ApiModelProperty(value = "检验项目44")
    private String test44;
    @ApiModelProperty(value = "检验项目45")
    private String test45;
    @ApiModelProperty(value = "检验项目46")
    private String test46;
    @ApiModelProperty(value = "检验项目47")
    private String test47;
    @ApiModelProperty(value = "检验项目48")
    private String test48;
    @ApiModelProperty(value = "检验项目49")
    private String test49;
    @ApiModelProperty(value = "检验项目50")
    private String test50;
    @ApiModelProperty(value = "检验项目51")
    private String test51;
    @ApiModelProperty(value = "检验项目52")
    private String test52;
    @ApiModelProperty(value = "检验项目53")
    private String test53;
    @ApiModelProperty(value = "检验项目54")
    private String test54;
    @ApiModelProperty(value = "检验项目55")
    private String test55;
    @ApiModelProperty(value = "检验项目56")
    private String test56;
    @ApiModelProperty(value = "检验项目57")
    private String test57;
    @ApiModelProperty(value = "检验项目58")
    private String test58;
    @ApiModelProperty(value = "检验项目59")
    private String test59;
    @ApiModelProperty(value = "检验项目60")
    private String test60;
    @ApiModelProperty(value = "检验项目61")
    private String test61;
    @ApiModelProperty(value = "检验项目62")
    private String test62;
    @ApiModelProperty(value = "检验项目63")
    private String test63;
    @ApiModelProperty(value = "检验项目64")
    private String test64;
    @ApiModelProperty(value = "检验项目65")
    private String test65;
    @ApiModelProperty(value = "检验项目66")
    private String test66;
    @ApiModelProperty(value = "检验项目67")
    private String test67;
    @ApiModelProperty(value = "检验项目68")
    private String test68;
    @ApiModelProperty(value = "检验项目69")
    private String test69;
    @ApiModelProperty(value = "检验项目70")
    private String test70;
    @ApiModelProperty(value = "检验项目71")
    private String test71;
    @ApiModelProperty(value = "检验项目72")
    private String test72;
    @ApiModelProperty(value = "检验项目73")
    private String test73;
    @ApiModelProperty(value = "检验项目74")
    private String test74;
    @ApiModelProperty(value = "检验项目75")
    private String test75;
    @ApiModelProperty(value = "检验项目76")
    private String test76;
    @ApiModelProperty(value = "检验项目77")
    private String test77;
    @ApiModelProperty(value = "检验项目78")
    private String test78;
    @ApiModelProperty(value = "检验项目79")
    private String test79;
    @ApiModelProperty(value = "检验项目80")
    private String test80;
    @ApiModelProperty(value = "检验项目81")
    private String test81;
    @ApiModelProperty(value = "检验项目82")
    private String test82;
    @ApiModelProperty(value = "检验项目83")
    private String test83;
    @ApiModelProperty(value = "检验项目84")
    private String test84;
    @ApiModelProperty(value = "检验项目85")
    private String test85;
    @ApiModelProperty(value = "检验项目86")
    private String test86;
    @ApiModelProperty(value = "检验项目87")
    private String test87;
    @ApiModelProperty(value = "检验项目88")
    private String test88;
    @ApiModelProperty(value = "检验项目89")
    private String test89;
    @ApiModelProperty(value = "检验项目90")
    private String test90;
    @ApiModelProperty(value = "检验项目91")
    private String test91;
    @ApiModelProperty(value = "检验项目92")
    private String test92;
    @ApiModelProperty(value = "检验项目93")
    private String test93;
    @ApiModelProperty(value = "检验项目94")
    private String test94;
    @ApiModelProperty(value = "检验项目95")
    private String test95;
    @ApiModelProperty(value = "检验项目96")
    private String test96;
    @ApiModelProperty(value = "检验项目97")
    private String test97;
    @ApiModelProperty(value = "检验项目98")
    private String test98;
    @ApiModelProperty(value = "检验项目99")
    private String test99;
    @ApiModelProperty(value = "检验项目100")
    private String test100;
    @ApiModelProperty(value = "")
    private String attribute1;
    @ApiModelProperty(value = "")
    private String attribute2;
    @ApiModelProperty(value = "")
    private String attribute3;
    @ApiModelProperty(value = "")
    private String attribute4;
    @ApiModelProperty(value = "")
    private String attribute5;
    @ApiModelProperty(value = "")
    private String attribute6;
    @ApiModelProperty(value = "")
    private String attribute7;
    @ApiModelProperty(value = "")
    private String attribute8;
    @ApiModelProperty(value = "")
    private String attribute9;
    @ApiModelProperty(value = "")
    private String attribute10;
    @ApiModelProperty(value = "")
    private String attribute11;
    @ApiModelProperty(value = "")
    private String attribute12;
    @ApiModelProperty(value = "")
    private String attribute13;
    @ApiModelProperty(value = "")
    private String attribute14;
    @ApiModelProperty(value = "")
    private String attribute15;
    @ApiModelProperty(value = "")
    private String attribute16;
    @ApiModelProperty(value = "")
    private String attribute17;
    @ApiModelProperty(value = "")
    private String attribute18;
    @ApiModelProperty(value = "")
    private String attribute19;
    @ApiModelProperty(value = "")
    private String attribute20;
    @ApiModelProperty(value = "")
    private String attribute21;
    @ApiModelProperty(value = "")
    private String attribute22;
    @ApiModelProperty(value = "")
    private String attribute23;
    @ApiModelProperty(value = "")
    private String attribute24;
    @ApiModelProperty(value = "")
    private String attribute25;
    @ApiModelProperty(value = "")
    private String attribute26;
    @ApiModelProperty(value = "")
    private String attribute27;
    @ApiModelProperty(value = "")
    private String attribute28;
    @ApiModelProperty(value = "")
    private String attribute29;
    @ApiModelProperty(value = "")
    private String attribute30;
    @ApiModelProperty(value = "")
    private String attribute31;
    @ApiModelProperty(value = "")
    private String attribute32;
    @ApiModelProperty(value = "")
    private String attribute33;
    @ApiModelProperty(value = "")
    private String attribute34;
    @ApiModelProperty(value = "")
    private String attribute35;
    @ApiModelProperty(value = "")
    private String attribute36;
    @ApiModelProperty(value = "")
    private String attribute37;
    @ApiModelProperty(value = "")
    private String attribute38;
    @ApiModelProperty(value = "")
    private String attribute39;
    @ApiModelProperty(value = "")
    private String attribute40;
    @ApiModelProperty(value = "")
    private String attribute41;
    @ApiModelProperty(value = "")
    private String attribute42;
    @ApiModelProperty(value = "")
    private String attribute43;
    @ApiModelProperty(value = "")
    private String attribute44;
    @ApiModelProperty(value = "")
    private String attribute45;
    @ApiModelProperty(value = "")
    private String attribute46;
    @ApiModelProperty(value = "")
    private String attribute47;
    @ApiModelProperty(value = "")
    private String attribute48;
    @ApiModelProperty(value = "")
    private String attribute49;
    @ApiModelProperty(value = "")
    private String attribute50;

    public void addErrorMessage(String message) {
        if (StringUtils.isNotBlank(message)) {
            this.processStatus = ERROR;
            this.processMessage = StringUtils.substring(Optional.ofNullable(this.processMessage).orElse("").concat(message), 0, 1999);
        }
    }
}
