package com.ruike.itf.api.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.Date;

/**
 * @author kejin.liu01@hand-china.com
 * @desc 物料，工单，物料组接口传参DTO
 * @return
 */
@Data
public class ItfSapIfaceDTO {
    // 物料接口
    private String UDATE;
    private String UTIME;
    private String ERFZEIT;
    private String PLVAR;
    private String bwkey;//BWKEY
    private String MMSTA;
    private String STRGR;
    private String VRKME;
    private Double ZUEETO;
    private String DISPO;
    private String BACKUPSEG2;
    private String BACKUPSEG1;
    @ApiModelProperty(value = "开封有效期（小时）")
    private String ZZKFYXDW;
    private String ALAND;
    private String EISLO;
    private String BESKZ;
    private String USEQU;
    private String BRGEW;
    @ApiModelProperty(value = "库存地点编码")
    private String LGORT;
    private String PEINH;
    private String STPRS;
    private String BACKUPSEG5;
    private String KORDB;
    private String PSTAT;
    @ApiModelProperty(value = "物料分类")
    private String ZZWLFL;
    private String BACKUPSEG4;
    private String BACKUPSEG3;
    @ApiModelProperty(value = "SN升级标识")
    private String ZZSNSJBS;
    private String MBRSH;
    private String ZPLP1;
    private String VKORG;
    private String UMREN;
    private String BSTME;
    private String PRCTR;
    private String DZEIT;
    private String TAKLV;
    private String BSTMI;
    private String KONDM;
    private String FHORI;
    private String MVGR1;
    private String DISGR;
    @ApiModelProperty(value = "激光器类型（01外箱条码，02内箱条码，03序列号条码）")
    private String ZZGUQLX;
    private String MVGR3;
    private String MVGR2;
    private String UMREZ;
    private String BSTMA;
    @ApiModelProperty(value = "最小包装")
    private String ZZIBZ;
    @ApiModelProperty(value = "工厂")
    private String WERKS;
    private String MTPOS;
    private String BKLAS;
    private String ART1;
    @ApiModelProperty(value = "开封有效期")
    private String ZZKFYX;
    private String ART2;
    private String ABCIN;
    private String LVORM;
    @ApiModelProperty(value = "旧物料号")
    private String BISMT;
    @ApiModelProperty(value = "物料类型")
    private String MTART;
    private String VTWEG;
    private String EISBE;
    private String BSTRF;
    @ApiModelProperty(value = "物料号")
    private String MATNR;
    private String VTEXT;
    @ApiModelProperty(value = "生产管理员")
    private String FEVOR;
    private String APA1;
    @ApiModelProperty(value = "库存地点")
    private String LGPRO;
    @ApiModelProperty(value = "虚拟标识")
    private String DUMPS;
    private String MTPOS_MARA;
    private String EXTWG;
    @ApiModelProperty(value = "物料分类")
    private String ZCPXH;
    @ApiModelProperty(value = "物料类型SN编码规则")
    private String ZCPSN;
    @ApiModelProperty(value = "基本计量单位")
    private String MEINS;
    private String VOLUM;
    private String TRAGR;
    private String KAUSF;
    private String DISMM;
    private String FABKZ;
    @ApiModelProperty(value = "产品组")
    private String SPART;
    private String MAABC;
    private String VOLEH;
    private String ZTMFS;
    private String GROES;
    @ApiModelProperty(value = "物料组")
    private String QMATV;
    @ApiModelProperty(value = "批次管理")
    private String XCHPF;
    private String WEBAZ;
    private String SOBSL;
    @ApiModelProperty(value = "储存时间")
    private String MAXLZ;
    private String BARCODE;
    @ApiModelProperty(value = "储存单位（天）")
    private String LZEIH;
    private String GEWEI;
    private String DISLS;
    private String ZGZDGL;
    private String APA2;
    @ApiModelProperty(value = "国内国外机（01国内，02国外）")
    private String ZGNW;
    @ApiModelProperty(value = "物料描述")
    private String MAKTX;
    @ApiModelProperty(value = "更新时间")
    private String LAEDA;
    @ApiModelProperty(value = "是否打印条码")
    private String ZSYTM;
    @ApiModelProperty(value = "删除标识（X删除，N失效，Y有效）")
    private String LVORM2;
    @ApiModelProperty(value = "保质期")
    private String ZZBQ;
    private String MINBE;
    private String EKGRP;
    @ApiModelProperty(value = "序列号参数文件")
    private String SERNP;
    private String ERSDA;
    @ApiModelProperty(value = "物料生产类型（SN序列号物料，LOT批次号物料，TIME时效物料）")
    private String ZZSCLX;
    private String SBDKZ;
    @ApiModelProperty(value = "反冲标识")
    private String RGEKZ;
    @ApiModelProperty(value = "功率大小")
    private String ZGL;
    private String NTGEW;
    private String WRKST;
    @ApiModelProperty(value = "保质期单位（天）")
    private String ZZBQDW;
    private String BUKEY;
    private String MSEHT;
    private String AKTIV2;
    private String AKTIV1;
    private String VERSG;
    private String EKALR;
    private String LADGR;
    private String MFRGR;
    private String BWTAR;
    private String VPRSV;
    private String ZPLD1;
    private String ERNAM;
    private String AENAM;
    private String LGFSB;
    private String BSTFE;
    private String PLIFZ;
    private String KTGRM;
    private String TAXM1;
    private String MTVFP;
    // 物料组接口
    @ApiModelProperty(value = "物料组编码")
    private String MATKL;
    @ApiModelProperty(value = "物料组描述")
    private String WGBEZ;
    private String SPRAS;
    @ApiModelProperty(value = "标准文本码描述")
    private String TXT;
    @ApiModelProperty(value = "标准文本码")
    private String VLSCH;
    @ApiModelProperty(value = "库存地点描述")
    private String LGOBE;
    @ApiModelProperty(value = "公司名称")
    private String NAME1;
    private String PICPOS;
    private String AEDAT;
    private String BERID;
    private String LMATN;
    private String PICKEY;
    private String SPERKZ;
    private String MRPGR;
    private String ERDAT;
    private String DATFR;
    private String PICGID;
    private String STLAN;
    @ApiModelProperty(value = "BOM版本")
    private String STLAL;
    private String ANDAT;
    private String LOSBS;
    private String ANNAM;
    @ApiModelProperty(value = "BOM编码")
    private String STLNR;
    @ApiModelProperty(value = "BOM描述")
    private String STKTX;
    private String LOSVN;
    private String ZHEADER;
    private String POTX1;
    @ApiModelProperty(value = "内部计数器")
    private Long STPOZ;
    private String POTX2;
    @ApiModelProperty(value = "起始时间")
    private Date DATUV;
    @ApiModelProperty(value = "结束时间时间")
    private Date DATUB;
    @ApiModelProperty(value = "组件用量")
    private Double MENGE;
    @ApiModelProperty(value = "组件报废")
    private Double AUSCH;
    private String SANFE;
    @ApiModelProperty(value = "替代组")
    private String ALPGR;
    private String SCHGT;
    @ApiModelProperty(value = "项目节点号")
    private String STLKN;
    @ApiModelProperty(value = "替代策略")
    private String ALPST;
    private String AENNR;
    @ApiModelProperty(value = "工序号")
    private String SORTF;
    private String RVREL;
    private String LKENZ;
    private String PSWRK;
    private String STLTY;
    @ApiModelProperty(value = "组件物料号")
    private String IDNRK;
    private String FMENG;
    private String OJTXP;
    @ApiModelProperty(value = "BOM项目号")
    private String POSNR;
    private String ZITEM;
    private String POSTP;
    @ApiModelProperty(value = "优先级")
    private String ALPRF;
    @ApiModelProperty(value = "使用百分比")
    private String EWAHR;
    @ApiModelProperty(value = "联产品")
    private String KZKUP;
    @ApiModelProperty(value = "联产品")
    //private Double BMEND;
    private Double BMENG;
    @ApiModelProperty(value = "结束时间")
    private Date BDATU;
    @ApiModelProperty(value = "生产版本")
    private String VERID;
    @ApiModelProperty(value = "描述")
    private String TEXT1;
    @ApiModelProperty(value = "开始时间")
    private Date ADATU;
    private String PRDAT;
    @ApiModelProperty(value = "组计数器")
    private String ALNAL;
    @ApiModelProperty(value = "是否锁定")
    private String PLNTY;
    @ApiModelProperty(value = "任务清单组键值")
    private String PLNNR;
    @ApiModelProperty(value = "是否锁定")
    private String MKSP;
    private String AUTYP;
    private String GSBER;
    @ApiModelProperty(value = "订单号")
    private String AUFNR;
    private String KOKRS;
    @ApiModelProperty(value = "描述")
    private String LTEXT;
    @ApiModelProperty(value = "订单描述")
    private String KTEXT;
    @ApiModelProperty(value = "工厂编码")
    private String BUKRS;
    @ApiModelProperty(value = "订单类型")
    private String AUART;
    private String REFNR;
    @ApiModelProperty(value = "销售订单号")
    private String KDAUF;
    @ApiModelProperty(value = "销售订单的项目编号")
    private String KDPOS;
    private String AUFEX;
    private String MANDT;
    @ApiModelProperty(value = "成本中心编码")
    private String KOSTL;
    @ApiModelProperty(value = "地点失效时间")
    private Date DATBI;
    private String ABTEI;
    @ApiModelProperty(value = "地点生效时间")
    private Date DATAB;
    @ApiModelProperty(value = "成本中心类型")
    private String KOSAR;  // 生产订单
    private String PWERK;
    @ApiModelProperty(value = "工厂")
    private String DWERK;
    private String KUNNR;
    @ApiModelProperty(value = "订单数量总计")
    private Double GAMNG;
    private String GMEIN;
    @ApiModelProperty(value = "订单开始时间")
    private String GSTRP;
    @ApiModelProperty(value = "订单结束时间")
    private String GLTRP;
    private String FTRMS;
    private String FTRMI;
    private String STAT;
    private String RSNUM;
    private String ABLAD;
    private String PLNAW;
    private String PLNAL;
    private String PVERW;
    private String PLAUF;
    private String PLSVB;
    private String PLNME;
    private String PLSVN;
    private String PDATV;
    private String STLST;
    private String SDATV;
    private String SBMNG;
    private String SBMEH;
    private String SAENR;
    private String SLSVN;
    private String SLSBS;
    private String AUFLD;
    @ApiModelProperty(value = "工单号")
    private String GDNUM;
    @ApiModelProperty(value = "工作指令")
    private String ZGNUM;
    @ApiModelProperty(value = "备注")
    private String ZBZHU;
    @ApiModelProperty(value = "长文本 ")
    private String ZTEXT;
    private String ZTEXT2;
    @ApiModelProperty(value = "基本单位")
    private String BASE_UOM;
    @ApiModelProperty(value = "损耗数量")
    private String ZZMENGE;
    @ApiModelProperty(value = "联产品行号")
    private String ORDER_ITEM_NUMBER;
    private String RSPOS;
    private String BDMNG;
    private String BDTER;
    private String ENMNG;
    private String XLOEK;
    private String VORNR;
    private String SOBKZ;
    private String BAUGR;
    private String XWAOK;
    private String KZEAR;
    private String XFEHL;
    private String ZZJXQ;
    @ApiModelProperty(value = "净需求单位用量")
    private String ZZJXQDWYL;
    private String ZZMXQDWYL;
    private String ZFLAG;
    private String AUFPL;
    private String LTXA1;
    private String STEUS;
    private String APLZL;
    private String LOEKZ;
    private String VGE01;
    private String VGW01;
    private String VGE02;
    private String VGW02;
    private String VGE03;
    private String VGW03;
    private String VGE04;
    private String VGW04;
    private String VGE05;
    private String VGW05;
    private String VGE06;
    private String VGW06;
    private String KTSCH;
    private String AEDAT_GRND;
    @ApiModelProperty(value = "开始时间")
    private Date BEGDA;
    private String AENAM_GRND;
    @ApiModelProperty(value = "工作中心")
    private String ARBPL;
    @ApiModelProperty(value = "结束时间")
    private Date ENDDA;
    private String OBJID;
    private String ZQMAT;
}
